version: "3.8"
services:
  postgres:
    image: postgres:16.4
    container_name: pg_recipe
    environment:
      POSTGRES_DB: recipedb
      POSTGRES_USER: recipe
      POSTGRES_PASSWORD: recipe
    ports:
      - "5432:5432"
    volumes:
      - pgdata_recipe:/var/lib/postgresql/data
      # healthcheck:
      #   test: ["CMD-SHELL", "pg_isready -U recipe -d recipedb"]
      #   interval: 10s
      #   timeout: 5s
      #   retries: 5
  recipe-manager:
    image: recipe-manager
    container_name: recipe-manager
    build:
      context: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - recipe-manager
volumes:
  pgdata_recipe:
