version: "3.8"
services:
  postgres:
    image: postgres:16.4
    container_name: pg_recipe
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata_recipe:/var/lib/postgresql/data
    healthcheck:
         test: ["CMD-SHELL", "pg_isready -U recipe -d recipedb"]
         interval: 5s
         timeout: 3s
         retries: 10
  recipe-manager:
    image: recipe-manager
    container_name: recipe-manager
    build:
      context: .
    ports:
      - "${APP_PORT:-8081}:8081"
    depends_on:
      - postgres
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - recipe-manager
volumes:
  pgdata_recipe:
