version: "3.8"
services:
  postgres:
    image: postgres:16.4
    container_name: pg_recipe
    environment:
      POSTGRES_DB: recipedb
      POSTGRES_USER: recipe
      POSTGRES_PASSWORD: recipe
    ports:
      - "5432:5432"
    volumes:
      - pgdata_recipe:/var/lib/postgresql/data
      # healthcheck:
      #   test: ["CMD-SHELL", "pg_isready -U recipe -d recipedb"]
      #   interval: 10s
      #   timeout: 5s
      #   retries: 5
volumes:
  pgdata_recipe:
