server:
  port: 8081

spring:
  application:
    name: recipe-manager

  datasource:
    # valoarea implicita cand rulezi IN CONTAINER (pe reteaua compose)
    url: jdbc:postgresql://${DB_HOST:pg_recipe}:${DB_PORT:5432}/${DB_NAME:recipedb}
    username: ${DB_USER:recipe}
    password: ${DB_PASSWORD:recipe}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none        # schema controlata de Flyway
    open-in-view: false
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

---
# suprascriere doar cand rulezi pe HOST (Java local)
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://${DB_HOST_LOCAL:localhost}:${DB_PORT_LOCAL:5432}/${DB_NAME:recipedb}
    username: ${DB_USER_LOCAL:${DB_USER:recipe}}
    password: ${DB_PASSWORD_LOCAL:${DB_PASSWORD:recipe}}